# Generated by Django 4.2.11 on 2025-03-18 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='類別名稱')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='類別代碼')),
                ('description', models.TextField(blank=True, null=True, verbose_name='類別描述')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_categories', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_product_categories', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '產品類別',
                'verbose_name_plural': '產品類別',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='品號')),
                ('product_name', models.CharField(max_length=100, verbose_name='品名')),
                ('specification', models.CharField(max_length=200, verbose_name='規格')),
                ('unit', models.CharField(max_length=20, verbose_name='單位')),
                ('box_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='裝箱容量')),
                ('status', models.BooleanField(default=True, verbose_name='狀態')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productcategory', verbose_name='類別')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_products', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '產品品號',
                'verbose_name_plural': '產品品號',
                'ordering': ['product_code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProductCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, editable=False, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='類別名稱')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='類別代碼')),
                ('description', models.TextField(blank=True, null=True, verbose_name='類別描述')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'historical 產品類別',
                'verbose_name_plural': 'historical 產品類別',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, editable=False, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('product_code', models.CharField(db_index=True, max_length=50, verbose_name='品號')),
                ('product_name', models.CharField(max_length=100, verbose_name='品名')),
                ('specification', models.CharField(max_length=200, verbose_name='規格')),
                ('unit', models.CharField(max_length=20, verbose_name='單位')),
                ('box_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='裝箱容量')),
                ('status', models.BooleanField(default=True, verbose_name='狀態')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.productcategory', verbose_name='類別')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'historical 產品品號',
                'verbose_name_plural': 'historical 產品品號',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='異動時間')),
                ('type', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '刪除')], max_length=10, verbose_name='異動類型')),
                ('product_code', models.CharField(db_index=True, max_length=50, verbose_name='品號')),
                ('field', models.CharField(max_length=50, verbose_name='異動欄位')),
                ('before_value', models.TextField(blank=True, verbose_name='變更前值')),
                ('after_value', models.TextField(blank=True, verbose_name='變更後值')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_histories', to=settings.AUTH_USER_MODEL, verbose_name='操作人員')),
            ],
            options={
                'verbose_name': '品號異動歷史',
                'verbose_name_plural': '品號異動歷史',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['-datetime'], name='product_pro_datetim_fddd9e_idx'), models.Index(fields=['product_code', '-datetime'], name='product_pro_product_89ecff_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['code'], name='product_pro_code_280a27_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['name'], name='product_pro_name_fd0d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_code'], name='product_pro_product_33b28d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_pro_categor_2b9d78_idx'),
        ),
    ]
