# Generated by Django 4.2.11 on 2024-12-25 07:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('line_user_id', models.CharField(max_length=100, unique=True, verbose_name='LINE User ID')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='顯示名稱')),
                ('status_message', models.TextField(blank=True, verbose_name='狀態消息')),
            ],
            options={
                'verbose_name': 'LINE用戶',
                'verbose_name_plural': 'LINE用戶',
                'db_table': 'line_user',
            },
        ),
        migrations.CreateModel(
            name='LineMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('message', models.TextField(verbose_name='消息內容')),
                ('message_type', models.CharField(max_length=50, verbose_name='消息類型')),
                ('is_sent', models.BooleanField(default=False, verbose_name='是否為發送')),
                ('line_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_bot.lineuser', verbose_name='LINE用戶')),
            ],
            options={
                'verbose_name': 'LINE消息',
                'verbose_name_plural': 'LINE消息',
                'db_table': 'line_message',
            },
        ),
    ]
