# Generated by Django 4.2.11 on 2024-12-27 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('line_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件類型')),
                ('file_url', models.URLField(verbose_name='文件URL')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('content_type', models.CharField(max_length=100, verbose_name='內容類型')),
            ],
            options={
                'verbose_name': 'LINE消息附件',
                'verbose_name_plural': 'LINE消息附件',
                'db_table': 'line_message_attachment',
            },
        ),
        migrations.AddField(
            model_name='linemessage',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='送達時間'),
        ),
        migrations.AddField(
            model_name='linemessage',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='錯誤信息'),
        ),
        migrations.AddField(
            model_name='linemessage',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='發送時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linemessage',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('sent', '已發送'), ('delivered', '已送達'), ('failed', '發送失敗')], default='pending', max_length=20, verbose_name='消息狀態'),
        ),
        migrations.AddField(
            model_name='lineuser',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='語言設定'),
        ),
        migrations.AddField(
            model_name='lineuser',
            name='last_interaction',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最後互動時間'),
        ),
        migrations.AddField(
            model_name='lineuser',
            name='picture_url',
            field=models.URLField(blank=True, null=True, verbose_name='頭像 URL'),
        ),
        migrations.AddField(
            model_name='lineuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_profile', to=settings.AUTH_USER_MODEL, verbose_name='系統用戶'),
        ),
        migrations.AlterField(
            model_name='linemessage',
            name='message_type',
            field=models.CharField(choices=[('text', '文字'), ('image', '圖片'), ('video', '視頻'), ('audio', '音頻'), ('file', '文件'), ('location', '位置'), ('sticker', '貼圖')], max_length=50, verbose_name='消息類型'),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='status_message',
            field=models.TextField(blank=True, null=True, verbose_name='狀態消息'),
        ),
        migrations.AddIndex(
            model_name='linemessage',
            index=models.Index(fields=['line_user', 'send_time'], name='line_messag_line_us_20723d_idx'),
        ),
        migrations.AddIndex(
            model_name='linemessage',
            index=models.Index(fields=['message_type'], name='line_messag_message_fd9c10_idx'),
        ),
        migrations.AddIndex(
            model_name='linemessage',
            index=models.Index(fields=['status'], name='line_messag_status_31e6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='lineuser',
            index=models.Index(fields=['line_user_id'], name='line_user_line_us_60408b_idx'),
        ),
        migrations.AddIndex(
            model_name='lineuser',
            index=models.Index(fields=['last_interaction'], name='line_user_last_in_f30c9b_idx'),
        ),
        migrations.AddField(
            model_name='linemessageattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='line_bot.linemessage'),
        ),
    ]
