# Generated by Django 4.2.11 on 2025-04-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0002_linemessageattachment_linemessage_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineuser',
            name='line_user_id',
            field=models.CharField(max_length=100, verbose_name='LINE User ID'),
        ),
        migrations.AlterUniqueTogether(
            name='lineuser',
            unique_together={('line_user_id', 'is_deleted')},
        ),
    ]
