# Generated by Django 4.2.11 on 2025-04-11 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('line_bot', '0003_alter_lineuser_line_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_profile', to=settings.AUTH_USER_MODEL, verbose_name='系統用戶'),
        ),
    ]
