# Generated by Django 4.2.11 on 2024-12-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_historicaldict_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_line_bound',
            field=models.BooleanField(default=False, verbose_name='是否綁定LINE'),
        ),
    ]
