# Generated by Django 4.2.11 on 2025-01-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_user_is_line_bound'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line_bind_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='LINE綁定時間'),
        ),
    ]
