# Generated by Django 4.2.11 on 2025-01-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_user_line_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='is_expired',
            field=models.BooleanField(default=False, verbose_name='是否已過期'),
        ),
    ]
