# Generated by Django 4.2.11 on 2025-04-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_user_birthday_user_id_number_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_number',
        ),
        migrations.AddField(
            model_name='user',
            name='mailing_address_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='通訊地址一'),
        ),
        migrations.AddField(
            model_name='user',
            name='mailing_address_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='通訊地址二'),
        ),
        migrations.AddField(
            model_name='user',
            name='personality_traits',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='人格特質'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='常用地址'),
        ),
    ]
