# Generated by Django 4.2.11 on 2025-04-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_remove_user_id_number_user_mailing_address_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='/media/default/avatar.png', max_length=255, null=True, verbose_name='大頭貼'),
        ),
    ]
